export const GET_ERRORS = "GET_ERRORS";
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SET_AUTHENTICATED_USER = "SET_AUTHENTICATED_USER";